<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllClientComments($ip)
    {
        return $this->createQueryBuilder('l')
            ->where(':ip = l.ip')
            ->setParameter('ip', $ip)
            ->getQuery()
            ->getArrayResult();
    }
}
