# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    twig.extensions:
        class: AppBundle\Twig\TwigExtensions
        tags:
            - { name: twig.extension }
        arguments:
            - '@app.current_user_data_service'
    app.current_user_data_service:
        class: AppBundle\Service\CurrentUserDataService
        arguments:
          - '@request_stack'


